encorelab/ck-board

src/app/app.component.html
src/app/app.component.scss
src/app/app.component.ts
src/app/app.module.ts
src/app/components/configuration-modal/configuration-modal.component.html
src/app/components/configuration-modal/configuration-modal.component.scss
src/app/components/configuration-modal/configuration-modal.component.spec.ts
src/app/components/configuration-modal/configuration-modal.component.ts
src/app/components/dialog/dialog.component.html
src/app/components/dialog/dialog.component.ts
src/app/components/post/post.component.html
src/app/components/post/post.component.ts
src/app/components/task-modal/task-modal.component.html
src/app/components/task-modal/task-modal.component.spec.ts
src/app/components/task-modal/task-modal.component.ts
src/app/interfaces/dialog.interface.ts
src/app/services/post.service.ts

- Added some styling to posts and canvas
- Added configuration settings button
- Added task viewing button

Added styling and config settings

---

src/app/app.component.ts
src/app/components/configuration-modal/configuration-modal.component.html
src/app/components/configuration-modal/configuration-modal.component.ts
src/app/components/dialog/dialog.component.ts
src/app/components/post/post.component.ts
src/app/interfaces/dialog.interface.ts
src/app/models/post.ts
src/app/services/config.service.ts
src/app/services/post.service.ts

Setup rough implementation of board permissions and configuration.
Added ability to lock movement of posts.
Closes #4

Allow posts to be locked

---

src/app/app.component.html
src/app/app.component.ts
src/app/components/configuration-modal/configuration-modal.component.html
src/app/components/configuration-modal/configuration-modal.component.ts

Users can now modify the board name and also set a background image for the canvas.
Closes #9

Allow title and bg-image to be set

---

src/app/app.component.ts

Canvas can now be zoomed in and out of. Dragging across the canvas is also configured.
Setting new background images will size the image to fit the current canvas size depending on zoom.
Closes #6

Added zooming/dragging of canvas

---

src/app/app.component.ts
src/app/components/dialog/dialog.component.html
src/app/components/dialog/dialog.component.ts
src/app/components/post/post.component.ts
src/app/interfaces/dialog.interface.ts

Added mandatory titles for posts and optional descriptions.
Closes #13

Added mandatory titles for posts w/ optional descs

---

src/app/app.component.html
src/app/app.component.scss
src/app/app.component.ts
src/app/app.module.ts
src/app/components/dialog/dialog.component.html
src/app/components/dialog/dialog.component.ts
src/app/components/post-modal/post-modal.component.html
src/app/components/post-modal/post-modal.component.spec.ts
src/app/components/post-modal/post-modal.component.ts
src/app/components/post/post.component.ts
src/app/models/post.ts
src/app/utils/ErrorStateMatcher.ts

- Added post editing (title and description)
- Added limits for title (50 chars) and descriptions (1000 chars)
- Canvas posts will display full title but up-to 200 characters for description, the rest can be viewed in the modal by simply clicking on the post
- Posts can be updated and deleted by clicking on post and choosing desired action
- Removed side buttons on home page and moved to a nav-bar above the canvas
Closes #2 
Closes #5 
Closes #7

Modal Design + Post Editing

---

src/app/app.component.ts
src/app/components/post-modal/post-modal.component.html
src/app/components/post-modal/post-modal.component.ts

Fixed delete post not working.
Added "Close" button to post modal.
Closes #32 
Closes #26

Fixed delete bug and added done button

---

src/app/app.component.html
src/app/app.component.ts
src/app/components/dialog/dialog.component.ts
src/app/components/post/post.component.ts
src/app/interfaces/dialog.interface.ts
src/app/utils/Mode.ts

User can choose a location to create a post, which will then pop a modal allowing the user to choose a title and description.
Closes #15

User picks location before creating post

---

src/app/app.module.ts
src/app/material-module.ts

Moved material modules to separate file

---

src/app/components/canvas/canvas.component.ts
src/app/components/post/post.component.ts

Instead of attaching listener to each post, added a global post listener that will open modal once a post is clicked.

Added global post-click listener

---

src/app/components/canvas/canvas.component.ts
src/app/models/config.ts
src/app/services/config.service.ts

Added config model

---

src/app/app-routing.module.ts

Any invalid urls and the `/` url will route to `/login`. 
Closes #57

Set default route to login screen

---

src/app/components/canvas/canvas.component.html

Only teachers can modify board settings

---

src/app/components/canvas/canvas.component.ts

Fixed zooming breaking new post's creation location

---

src/app/components/add-post-modal/add-post.component.html
src/app/components/add-post-modal/add-post.component.ts

Changed desc -> message and added textarea

---

src/app/components/canvas/canvas.component.ts
src/app/components/configuration-modal/configuration-modal.component.html
src/app/components/configuration-modal/configuration-modal.component.ts
src/app/components/task-modal/task-modal.component.html
src/app/components/task-modal/task-modal.component.ts
src/app/material-module.ts
src/app/models/board.ts

- Redesigned settings modal
- Allowed user to edit task
- Current board name, task details are shown in the textboxes on modal launch
Closes #51 
Closes #50

Made task editable + redesigned settings modal

---

src/app/app-routing.module.ts
src/app/components/canvas/canvas.component.ts
src/app/components/login/login.component.ts
src/app/components/register/register.component.ts
src/app/services/auth.service.ts
src/app/services/board.service.ts
src/app/utils/auth.guard.ts
src/app/utils/board.guard.ts

- Authentication is all handled in its service class now
- Multiple boards will now be routed to their own url

Refactored authentication and opened room to handle multiple boards

---

src/app/components/canvas/canvas.component.ts

- Able to click on posts in any mode
Closes #70

Click posts while in pan mode

---

src/app/components/canvas/canvas.component.ts
src/app/components/post-modal/post-modal.component.html
src/app/components/post-modal/post-modal.component.ts
src/app/components/post/post.component.ts
src/app/utils/FabricUtils.ts

- Now storing user's id in post
- Only authors can edit/delete their notes
- Teachers can edit/delete any note
Closes #31

Only authors + teachers can edit/delete their notes

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/add-board-modal/add-board-modal.component.html
src/app/components/add-board-modal/add-board-modal.component.spec.ts
src/app/components/add-board-modal/add-board-modal.component.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.scss
src/app/components/dashboard/dashboard.component.spec.ts
src/app/components/dashboard/dashboard.component.ts
src/app/material-module.ts
src/app/services/auth.service.ts
src/app/services/board.service.ts

- View all boards created
- Create board 
- Navigate to specific board
- TBD styling/design
Closes #75

Added basic dashboard

---

src/app/components/add-board-modal/add-board-modal.component.html
src/app/components/configuration-modal/configuration-modal.component.html

- Allowing .jpg, .jpeg, .png, .svg
Closes #80

Only allow images for canvas bg

---

src/app/components/canvas/canvas.component.html
src/app/material-module.ts

- Added button to return to dash from canvas
- Added tooltips for buttons in canvas so users know what each button briefly does
Closes #81

Added button to return to dash from canvas

---

src/app/components/add-board-modal/add-board-modal.component.html
src/app/components/add-board-modal/add-board-modal.component.scss
src/app/components/add-board-modal/add-board-modal.component.ts
src/app/components/canvas/canvas.component.ts
src/app/components/configuration-modal/configuration-modal.component.html
src/app/components/configuration-modal/configuration-modal.component.scss
src/app/components/configuration-modal/configuration-modal.component.ts
src/app/components/dashboard/dashboard.component.ts
src/app/components/post-modal/post-modal.component.html
src/app/components/post-modal/post-modal.component.scss
src/app/components/post-modal/post-modal.component.ts
src/app/material-module.ts
src/app/models/board.ts
src/app/models/post.ts
src/app/services/post.service.ts

Implemented tagging within a post's modal.
- Students can add or remove tags from inside a post's modal
- Teachers can add or remove tags from the settings modal
For V2, we should probably show a limited number of tags on the actual post itself as well.

Tagging V1

---

angular.json
src/app/app-routing.module.ts
src/app/components/canvas/canvas.component.ts
src/app/components/dashboard/dashboard.component.ts
src/app/services/auth.service.ts
src/app/utils/auth.guard.ts
src/app/utils/board.guard.ts

Fixed routing issues related to refreshing pages and visiting pages using a direct URL.
Closes #99

Fixed routing issues

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/add-board-modal/add-board-modal.component.html
src/app/components/add-board-modal/add-board-modal.component.ts
src/app/components/canvas/canvas.component.ts
src/app/components/configuration-modal/configuration-modal.component.html
src/app/components/configuration-modal/configuration-modal.component.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/dashboard/dashboard.component.scss
src/app/components/dashboard/dashboard.component.ts
src/app/components/error/error.component.html
src/app/components/error/error.component.scss
src/app/components/error/error.component.spec.ts
src/app/components/error/error.component.ts
src/app/components/join-board-modal/join-board-modal.component.html
src/app/components/join-board-modal/join-board-modal.component.spec.ts
src/app/components/join-board-modal/join-board-modal.component.ts
src/app/components/login/login.component.ts
src/app/components/register/register.component.ts
src/app/material-module.ts
src/app/models/board.ts
src/app/models/user.ts
src/app/services/auth.service.ts
src/app/services/board.service.ts
src/app/services/user.service.ts
src/app/utils/Utils.ts
src/app/utils/auth.guard.ts
src/app/utils/board.guard.ts

- When creating or editing board settings, you can choose to make board `public` or `private`
- Dashboard is split into 2 sections now: `Your Boards` and `Public Boards`
- Dashboard navigation bar has new button which allows user to join new boards using an invite code
Closes #97

ISSUE-97: Adds private/public boards with join codes

---

src/app/components/add-board-modal/add-board-modal.component.html
src/app/components/add-board-modal/add-board-modal.component.ts
src/app/components/canvas/canvas.component.ts
src/app/components/configuration-modal/configuration-modal.component.html
src/app/components/post-modal/post-modal.component.html
src/app/components/post-modal/post-modal.component.ts
src/app/models/permissions.ts
src/app/utils/FabricUtils.ts

- Added options in add-board and configuration-modal to hide author names from students and from teachers
- When "show author names" is unchecked, author names will appear as Anonymous to other students
Closes #14

Issue 14 hide author option

---

src/app/components/canvas/canvas.component.ts
src/app/components/configuration-modal/configuration-modal.component.html
src/app/components/configuration-modal/configuration-modal.component.scss
src/app/components/configuration-modal/configuration-modal.component.ts
src/app/utils/FabricUtils.ts

- Added a new `Remove Background Image` button which is self-explanatory
- Restricted image uploads to `.png` and `.svg` since `.jpeg/.jpg` are very large when encoded to strings
Note: In the future, we should look to move to alternate image storing service which will allow us to store larger images. Or, find a way to compress `.jpg` images.
Closes #89

ISSUE-89: Image Upload Bugs

---

src/app/components/add-board-modal/add-board-modal.component.html
src/app/components/add-project-modal/add-project-modal.component.html

- Project name is required when creating projects
- Board name and project is required when creating boards
Closes #143

Issue 143 require board names

---

src/app/components/canvas/canvas.component.ts

- updates to author name visibility reflect immediately for all users 
Closes #129

Issue 129 update author name visibility

---

src/app/utils/FabricUtils.ts

- Fixed background image skew by scaling width and height evenly
Closes #95

Issue 95 background image skewed

---

angular.json
package.json
src/app/app.module.ts

- Removed unused `ngx-infinite-scroll` dependency
- Increased budget for `error.component.scss` due to import

Removed unused dep and upped scss budget

---

src/app/app-routing.module.ts

Change default route to login not error page

---

src/app/components/add-post-modal/add-post.component.html
src/app/components/canvas/canvas.component.ts
src/app/material-module.ts

- Show snackbar when user clicks "+" button to create post, to show that they should choose the to-be-created post's location.
- Put focus on the title input field on the new post form.
Closes #182

ISSUE-182: "Place Post" Message

---

src/app/components/html-post/html-post.component.html
src/app/components/html-post/html-post.component.ts

- Display author names correctly on bucket posts
Closes #171

ISSUE 171 fix author names on bucketposts

---

src/app/components/canvas/canvas.component.ts

- Lock arrow keys on modal open
- Unlock arrow keys when all modals close 
Closes #169

ISSUE 169 added subscription to lock/unlock arrow keys

---

src/app/components/add-post-modal/add-post.component.html
src/app/components/add-post-modal/add-post.component.scss
src/app/components/add-post-modal/add-post.component.ts
src/app/components/canvas/canvas.component.ts
src/app/components/fabric-post/fabric-post.component.ts

- Allows users to apply tags when creating a new post
Closes #168

ISSUE-168: Choose tags on post creation

---

src/app/components/list-modal/list-modal.component.html
src/app/components/list-modal/list-modal.component.scss
src/app/components/list-modal/list-modal.component.ts
src/app/models/board.ts

- Filter by tags in list view
- Only posts that contain all of the filter tags will be displayed
Closes #177

Issue 177 filter tags list view

---

src/app/components/snackbar/snackbar.component.html
src/app/components/snackbar/snackbar.component.ts
src/app/components/task-modal/task-modal.component.html
src/app/components/task-modal/task-modal.component.ts

- Hyperlink text within the task modal and the snackbars
Closes #218

ISSUE-218: Hyperlink tasks in snackbar and task modal

---

src/app/components/add-post-modal/add-post.component.ts
src/app/components/buckets-modal/buckets-modal.component.ts
src/app/components/canvas/canvas.component.ts
src/app/interfaces/dialog.interface.ts

- Correctly sets the post background color on creation.
Closes #212

ISSUE-212: Fix post background colour

---

src/app/components/html-post/html-post.component.ts
src/app/components/list-modal/list-modal.component.ts
src/app/services/post.service.ts

- Updated filtered list view posts when posts are created/deleted and when tags are added/removed
Closes #222

Issue 222 update filtered posts on post crud

---

src/app/components/add-post-modal/add-post.component.ts
src/app/components/buckets-modal/buckets-modal.component.ts
src/app/components/canvas/canvas.component.ts
src/app/components/fabric-post/fabric-post.component.ts
src/app/components/post-modal/post-modal.component.ts
src/app/utils/FabricUtils.ts
src/app/utils/constants.ts

- Updated post to have red border for posts that are tagged with the "Needs Attention" tag
Closes #217

ISSUE-217: Add Red Border on "Needs Attention" tagged posts

---

src/app/components/buckets-modal/buckets-modal.component.html
src/app/components/buckets-modal/buckets-modal.component.scss
src/app/components/canvas/canvas.component.ts
src/app/components/dashboard/dashboard.component.html
src/app/components/html-post/html-post.component.html
src/app/components/html-post/html-post.component.scss
src/app/components/list-modal/list-modal.component.html
src/app/components/list-modal/list-modal.component.scss
src/app/components/project-dashboard/project-dashboard.component.html
src/style/layout/_post-list.scss

- Increases buckets and post list dialog max width.
- Adds a close button to dialogs.
- Adds responsiveness to post lists and increases html post width.
- Cleans up html post styles.
- Adds keyboard accessibility to html posts.
Closes #197.

ISSUE-197: Resize buckets/list-view posts

---

src/app/components/create-workflow-modal/create-workflow-modal.component.html
src/app/components/create-workflow-modal/create-workflow-modal.component.ts
src/app/services/bucket.service.ts
src/app/services/snackbar.service.ts

- Keep modal open after creating new bucket.
Note: You may have noticed snackbar design/colors are off. We can handle those in a separate issue.
Closes #193

ISSUE-193: Keep workflows open after create bucket

---

src/app/components/canvas/canvas.component.ts

ISSUE-239: Fix Background Image Removal

---

src/app/components/canvas/canvas.component.ts
src/app/components/list-modal/list-modal.component.html
src/app/components/list-modal/list-modal.component.ts

-  Option to add posts in list view
Closes #246

Issue 246 create post in list view

---

src/app/components/configuration-modal/configuration-modal.component.html
src/app/components/configuration-modal/configuration-modal.component.ts
src/app/models/board.ts
src/app/utils/board.guard.ts
src/app/utils/project.board.guard.ts

- Removed public board from board configuration
Closes #228

Issue 228 removed public board from board configuration

---

package.json
src/app/app.module.ts
src/app/components/canvas/canvas.component.html
src/app/components/canvas/canvas.component.ts
src/app/components/notification-dropdown/notification-dropdown.component.html
src/app/components/notification-dropdown/notification-dropdown.component.spec.ts
src/app/components/notification-dropdown/notification-dropdown.component.ts
src/app/components/post-modal/post-modal.component.ts
src/app/models/notification.ts
src/app/services/canvas.service.ts
src/app/services/comment.service.ts
src/app/services/likes.service.ts
src/app/services/notification.service.ts
src/app/services/post.service.ts

- User will be notified whenever a user comments, tags or likes their posts
- no option to turn on/off notifications yet (should I add this?)
- When a user clicks on a notification, the post modal opens and the notification is marked as viewed
- For now notifications are deleted after they have been viewed
- Mark all as read will mark all notifications as read
Closes #213

Issue 213 notification system

---

src/app/components/add-board-modal/add-board-modal.component.ts
src/app/components/canvas/canvas.component.ts
src/app/components/configuration-modal/configuration-modal.component.html
src/app/components/configuration-modal/configuration-modal.component.scss
src/app/components/configuration-modal/configuration-modal.component.ts
src/app/material-module.ts
src/app/models/board.ts
src/styles.scss

- Field to set initial zoom in board configuration
- Fixed bugs with background image upload
- When the background image is updated, the initial zoom is reset to 100%
Closes #234

Issue 234 set default zoom

---

src/app/components/fabric-post/fabric-post.component.ts
src/app/utils/FabricUtils.ts

- When a post has no comments, comment count will be hidden
- When a post has a least one comment, comment count will be displayed
Closes #138

Issue 138 show comment icon only after first comment

---

src/app/components/post-modal/post-modal.component.html

- User can now also post a comment by simply pressing the Enter key
Closes #262

Submit comment by pressing enter

---

src/app/components/canvas/canvas.component.ts
src/app/services/snackbar.service.ts

- Read Task icon on the board now only queues a snackbar if there's none currently open 
Closes #230

Make read task snackbar toggleable

---

frontend/src/app/components/login/login.component.ts
frontend/src/app/guards/auth.guard.ts
frontend/src/app/services/user.service.ts

- Logged out users accessing a specific page get directed to login page, then redirected to destination after logging in
Closes #295

Issue 295 - Redirect from login page to destination URL

---

backend/src/models/Tag.ts
backend/src/socket/trace/post.trace.ts
frontend/src/app/components/add-board-modal/add-board-modal.component.ts
frontend/src/app/components/buckets-modal/buckets-modal.component.ts
frontend/src/app/components/configuration-modal/configuration-modal.component.ts
frontend/src/app/components/csv-download-button/traceDefaults.ts
frontend/src/app/components/list-modal/list-modal.component.ts
frontend/src/app/components/login/login.component.ts
frontend/src/app/components/post-modal/post-modal.component.ts
frontend/src/app/models/tag.ts
frontend/src/app/utils/FabricUtils.ts

- TagID created for all new tags added to a board
Closes #226

tagID for new tags

---

backend/src/api/upvotes.ts
frontend/src/app/components/canvas/canvas.component.ts

- Fixes bug where teacher updating the upvote limit wouldn't propagate correctly to students without refreshing.
- Change upvote limit message.
Closes #300

Issue 300 - Fix upvote update issue

---

frontend/src/app/app.module.ts
frontend/src/app/autofocus.directive.spec.ts
frontend/src/app/autofocus.directive.ts
frontend/src/app/components/add-post-modal/add-post.component.html
frontend/src/app/components/add-post-modal/add-post.component.ts
frontend/src/app/components/buckets-modal/buckets-modal.component.ts
frontend/src/app/components/canvas/canvas.component.ts
frontend/src/app/components/html-post/html-post.component.html
frontend/src/app/components/html-post/html-post.component.ts
frontend/src/app/components/list-modal/list-modal.component.ts
frontend/src/app/components/login/login.component.ts
frontend/src/app/components/post-modal/post-modal.component.html
frontend/src/app/components/post-modal/post-modal.component.ts

- When creating new post focus in on title field
- When post comments are clicked, focus is panned to the comment field
Closes #298

focus on input fields

---

frontend/src/app/components/buckets-modal/buckets-modal.component.ts
frontend/src/app/components/fabric-post/fabric-post.component.ts
frontend/src/app/components/html-post/html-post.component.html
frontend/src/app/components/list-modal/list-modal.component.ts
frontend/src/app/components/login/login.component.ts
frontend/src/app/components/post-modal/post-modal.component.html
frontend/src/app/components/post-modal/post-modal.component.ts

- Icons changed to upwards and downwards triangles
Post List Modal:
Canvas:
Closes #306

Change voting icons

---

LICENSE

- Quickly added the GNU Public License, lmk if there is anything else we need to add related to Licensing
Closes #325

Added GNU LICENSE

---

frontend/src/app/components/post-modal/post-modal.component.ts

- Did a quick fix so that links will be updated instantly when a post is edited in the post modal
Closes #347

Quick fix Update links when editing post

---

backend/src/socket/events/notification.events.ts
backend/src/socket/socket.ts
frontend/src/app/components/post-modal/post-modal.component.html

- Quick fix for comments
Closes #370

Quick fix for comments

---

frontend/src/app/components/add-project-modal/add-project-modal.component.ts
frontend/src/app/components/toolbar/toolbar.component.html

- Link to SCORE added below the logout button in the toolbar.
Closes #367

Link to SCORE

---

frontend/src/app/components/create-workflow-modal/create-workflow-modal.component.html

View is now like this:
Closes #375

Changes made to Create Workflow Modal

---

frontend/src/app/services/canvas.service.ts

- Small change: add a POST_CREATE trace along with the BUCKET_ADD_POST trace when adding posts from the bucket modal.
Closes #353

Issue 353 - Bucket Post Create Log

---

frontend/.eslintrc.json
frontend/src/app/components/add-board-modal/add-board-modal.component.html
frontend/src/app/components/add-board-modal/add-board-modal.component.ts
frontend/src/app/components/canvas/canvas.component.html
frontend/src/app/components/ck-workspace/ck-workspace.component.html
frontend/src/app/components/configuration-modal/configuration-modal.component.html
frontend/src/app/components/configuration-modal/configuration-modal.component.ts
frontend/src/app/components/create-workflow-modal/create-workflow-modal.component.html
frontend/src/app/components/html-post/html-post.component.html
frontend/src/app/components/html-post/html-post.component.ts
frontend/src/app/components/project-dashboard/project-dashboard.component.ts
frontend/src/app/utils/converters.ts

- Addresses all bugs in the issues below
- I made sure to double check each issue, but please let me know if I may have missed something 👍 
Closes #408, Closes #407, Closes #385, Closes #393, Closes #410, Closes #403, Closes #398, Closes #396, Closes #395, Closes #386
(repeated closes since thats the only way to link multiple issues to one PR)

Ck-board Bug fixes 

---

backend/src/api/groups.ts
backend/src/api/todoItem.ts
backend/src/models/TodoItem.ts
backend/src/repository/dalGroup.ts
backend/src/repository/dalTodoItem.ts
frontend/src/app/components/add-todo-list-modal/add-todo-list-modal.component.html
frontend/src/app/components/add-todo-list-modal/add-todo-list-modal.component.scss
frontend/src/app/components/add-todo-list-modal/add-todo-list-modal.component.ts
frontend/src/app/components/todo-list-modal/todo-list-modal.component.html
frontend/src/app/components/todo-list-modal/todo-list-modal.component.scss
frontend/src/app/components/todo-list-modal/todo-list-modal.component.ts
frontend/src/app/models/todoItem.ts
frontend/src/app/services/group.service.ts
frontend/src/app/services/todoItem.service.ts
frontend/src/app/utils/constants.ts

- Implemented Group Todo list feature which functions like TODO List 
- Can edit/restore group todo list tasks
- Todo list task types also implemented
Closes #381, Closes #390

Group TODO List Feature implemented

---

frontend/src/app/components/ck-monitor/ck-monitor.component.html
frontend/src/app/components/ck-monitor/ck-monitor.component.scss

- Fix navbar to top in ck monitor view
Closes #430

ISSUE-430: Fix navbar to top

---

backend/src/socket/events/post.events.ts
frontend/src/app/components/ck-monitor/ck-monitor.component.html
frontend/src/app/components/ck-monitor/ck-monitor.component.scss

navbar HOTFIX

---

frontend/src/app/components/post-modal/post-modal.component.html
frontend/src/app/components/post-modal/post-modal.component.ts
frontend/src/app/services/canvas.service.ts

- Can now add/remove a post from the board through its post modal
Closes #428

ISSUE-428: Toggle post between board/bucket through post modal

---

frontend/src/app/components/add-todo-list-modal/add-todo-list-modal.component.html
frontend/src/app/components/add-todo-list-modal/add-todo-list-modal.component.ts
frontend/src/app/utils/constants.ts

- Increase max todo title length to 100

Increase max todo title length to 100

---

backend/src/api/posts.ts
backend/src/repository/dalPost.ts
backend/src/utils/api.helpers.ts
frontend/src/app/components/buckets-modal/buckets-modal.component.html
frontend/src/app/components/buckets-modal/buckets-modal.component.scss
frontend/src/app/components/buckets-modal/buckets-modal.component.ts
frontend/src/app/components/ck-workspace/ck-workspace.component.html
frontend/src/app/components/ck-workspace/ck-workspace.component.scss
frontend/src/app/components/ck-workspace/ck-workspace.component.ts
frontend/src/app/material-module.ts
frontend/src/app/services/post.service.ts

- Posts will be loaded in smaller chunks in the bucket modal (you can set how many per page)
- When opening a workspace activity, there will be a spinner before everything for that activity is loaded
Closes #426

ISSUE-426: Paginate bucket posts + spinner loader icon for workspace

---

frontend/src/app/app.module.ts

- Fix background image upload bug
Closes #450

ISSUE-450: Fix background image upload bug

---

frontend/src/app/components/post-modal/post-modal.component.ts

- Post description in post modal will include new lines 
Closes #456

Add line breaks in post description

---

backend/src/api/boards.ts
backend/src/repository/dalBoard.ts
frontend/src/app/components/add-post-modal/add-post.component.html
frontend/src/app/components/add-post-modal/add-post.component.ts
frontend/src/app/components/canvas/canvas.component.ts
frontend/src/app/components/post-modal/post-modal.component.ts
frontend/src/app/components/project-configuration-modal/project-configuration-modal.component.ts
frontend/src/app/components/project-dashboard/project-dashboard.component.ts
frontend/src/app/services/board.service.ts

- Copy to Personal Boards button added
- Viewable to Teacher from any Personal Board
- Creating post in Boards will be copied to other Personal Boards, and creating posts in List view will be copied to other list views
Closes #458

Add copy to Personal Boards button

---

frontend/src/app/components/ck-monitor/ck-monitor.component.html
frontend/src/app/components/ck-monitor/ck-monitor.component.scss

- prevent sidebar buttons from overflowing in ck-monitor + code style changes
Closes #468

Fix [468]: ck-monitor button overflow

---

frontend/src/app/components/create-workflow-modal/create-workflow-modal.component.ts

- post per buckets no longer required for other non-random workflow distributions
Closes #477

fix: [477] correctly map required fields

---

frontend/src/app/components/canvas/canvas.component.html
frontend/src/app/components/canvas/canvas.component.ts
frontend/src/app/components/ck-monitor/ck-monitor.component.html
frontend/src/app/components/ck-monitor/ck-monitor.component.ts
frontend/src/app/components/ck-workspace/ck-workspace.component.html
frontend/src/app/components/ck-workspace/ck-workspace.component.ts
frontend/src/app/components/csv-download-button/csv-download-button.component.html
frontend/src/app/components/dashboard/dashboard.component.html
frontend/src/app/components/project-dashboard/project-dashboard.component.html
frontend/src/app/components/project-dashboard/project-dashboard.component.ts
frontend/src/app/components/toolbar/toolbar.component.html
frontend/src/app/components/toolbar/toolbar.component.scss
frontend/src/app/components/toolbar/toolbar.component.ts

- Hamburger Icon Menu in both Project Dashboard and Canvas for student and teacher views
- Reveals list of Icons + Icon Function when clicked
Closes #463

(FEAT): Hamburger Dropdown for navbar icons

---

backend/src/agents/workflow.agent.ts
backend/src/api/workflows.ts
backend/src/socket/events/post.events.ts
frontend/src/app/components/ck-workspace/ck-workspace.component.html
frontend/src/app/components/ck-workspace/ck-workspace.component.ts
frontend/src/app/components/html-post/html-post.component.ts
frontend/src/app/components/post-modal/post-modal.component.ts
frontend/src/app/services/workflow.service.ts

- To avoid the issues caused by websockets when working in the workspace components, we're switching to all the updates being done through HTTP, to improve reliability
Closes #476

ISSUE-476: Change workspace actions to HTTP from websockets

---

frontend/src/app/components/canvas/canvas.component.ts
frontend/src/app/components/ck-monitor/ck-monitor.component.html
frontend/src/app/components/ck-monitor/ck-monitor.component.scss
frontend/src/app/components/ck-workspace/ck-workspace.component.html
frontend/src/app/components/ck-workspace/ck-workspace.component.scss
frontend/src/app/components/project-todo-list-modal/project-todo-list-modal.component.html
frontend/src/app/components/project-todo-list-modal/project-todo-list-modal.component.scss
frontend/src/app/components/todo-list-modal/todo-list-modal.component.html
frontend/src/app/utils/FabricUtils.ts

- Removes Grey bar at the bottom of screen from all embeddable views
- Removed Grey bar seen at the bottom of both CK-Monitor and CK-Workspace
Closes #506

(FIX): Removed Grey bar from all embeddable URL views and CK-Monitor

---

frontend/src/app/components/add-post-modal/add-post.component.html
frontend/src/app/components/add-post-modal/add-post.component.scss
frontend/src/app/components/add-post-modal/add-post.component.ts
frontend/src/app/services/post.service.ts
frontend/src/app/utils/interceptor.ts

- When post is bring created, the "create post" button will be disabled until completion
- Added snackbars in case of error or if post is successfully created
Closes #509

ISSUE-509: Disable button while post is being created

---

frontend/src/app/components/confirm-modal/confirm-modal.component.html
frontend/src/app/components/confirm-modal/confirm-modal.component.ts
frontend/src/app/components/groups/manage-group-modal/manage-group-modal.component.html
frontend/src/app/components/groups/manage-group-modal/manage-group-modal.component.scss
frontend/src/app/components/groups/manage-group-modal/manage-group-modal.component.ts
frontend/src/app/components/groups/move-group-members/move-group-members.component.ts

- Added confirmation modals and UI improvements
Closes #342

feat [342]: update group modal UI flow

---

backend/src/models/TodoItem.ts
frontend/src/app/components/add-todo-list-modal/add-todo-list-modal.component.html
frontend/src/app/components/add-todo-list-modal/add-todo-list-modal.component.ts
frontend/src/app/models/todoItem.ts
frontend/src/app/utils/constants.ts

chore [529]: add ATL todo type

---

backend/src/socket/events/post.events.ts
frontend/src/app/components/add-post-modal/add-post.component.ts
frontend/src/app/components/canvas/canvas.component.ts

- Fixed the bug where in the embedded personal boards view, posts were being sent to all other personal boards on creation
- Turned out to be a small SocketEvent emitting error; now fixed
Closes #538

(BUG-FIX): Posts created in personal boards dont show up in other personal boards

---

frontend/src/app/components/add-learner-modal/add-learner-modal.component.html
frontend/src/app/components/add-learner-modal/add-learner-modal.component.ts
frontend/src/app/utils/highchart.ts

- Address comments missed in #523

Remove modal tabs and rename export button text

---

frontend/src/app/services/snackbar.service.ts

- Added snackbar duration config to close all snackbars in 5 seconds
Closes #553

Close all snackbars after 5 seconds

---

frontend/src/app/components/add-board-modal/add-board-modal.component.html
frontend/src/app/components/add-project-modal/add-project-modal.component.html
frontend/src/app/components/add-project-modal/add-project-modal.component.scss
frontend/src/app/components/canvas/canvas.component.html
frontend/src/app/components/configuration-modal/configuration-modal.component.html

chore [568]: update modal labels

---

frontend/src/app/components/view-navigation/view-navigation.component.scss

Added styling to view tabs
- Set colour to tabs, round top corners of buttons, adjusts nav bar spacing, make selected tab distinct
Closes #580

Add styling for view tabs and adjust nav bar spacing

---

frontend/src/app/components/project-dashboard/project-dashboard.component.html

Moved the three dots menu from the mat-card into mat-card-title
Closes #591

Fixed the three dots menu issue on project-dashboard

---

.github/workflows/linter.yml
README.md
backend/src/socket/socket.ts

Reconcile discrepancies and merge new port origin for redis server into master

Master <- Develop

---

README.md
backend/src/server.ts
backend/src/socket/socket.ts
frontend/src/app/app.module.ts
frontend/src/app/utils/interceptor.ts
frontend/src/environments/environment.prod.ts
frontend/src/environments/environment.ts

Used angular environment variables and backend .env file to avoid hardcoding dev and production URLs. Also, updated the web sockets port to fix port connection issue on production. 
- Test logging and navigating between pages to ensure new configurations are correct
- Check browser console while on canvas to ensure that no web socket errors appear
Closes #610

Fixed hardcoding dev/prod URLs and web socket port

---

backend/src/services/vertexAI/index.ts
frontend/src/app/components/create-workflow-modal/create-workflow-modal.component.ts

- Added special character escaping and server-side
- Updated JSON markdown removal to suppose cases of nested coding markdown quotes
Closes #623

Added server-side escaping of AI Assistant generated JSON special characters

---

backend/src/services/vertexAI/index.ts
backend/src/socket/socket.ts
frontend/src/app/components/post-modal/post-modal.component.html
frontend/src/app/components/post-modal/post-modal.component.ts
frontend/src/app/components/project-dashboard/project-dashboard.component.html
frontend/src/app/components/task-modal/task-modal.component.ts
frontend/src/app/components/toolbar-menu/toolbar-menu.component.html
frontend/src/app/components/toolbar/toolbar.component.html
frontend/src/app/services/socket.service.ts

Added miscellaneous minor improvements to posts, tasks, AI assistant, and socket handling
- Removed manual bucket moving of posts option from students
- Added author information to AI Assistant context information
- Removed Go to SCORE from menu
- Added additional socket error handling, especially on client side
- Added styling to maintain newline and indentation formatting in Task and Post contents
**Test:**
- Check that students lose access to the add_library icon in their posts to add or remove posts from buckets
- Ensure AI can access context about which student authored which posts
- Ensure "Go to SCORE" menu option is removed for teachers and students
- Verify that sockets still perform as expected
- Verify that opening and viewing posts and View Full Task now preserve indentation …

632 feature add oct 29 2024 research study request updates

---

frontend/src/app/components/ck-workspace/ck-workspace.component.html
frontend/src/app/components/ck-workspace/ck-workspace.component.ts
frontend/src/app/components/html-post/html-post.component.ts
frontend/src/app/components/post-modal/post-modal.component.ts

If a student deletes a post during a generation task after having created one, the progress bar decreases and the task requires one more post to be completed.
- 
Closes #640

640 bug handle deleting post during generation workflow

---

backend/src/agents/workflow.agent.ts
backend/src/api/workflows.ts
backend/src/models/GroupTask.ts
backend/src/models/Workflow.ts
backend/src/repository/dalGroupTask.ts
frontend/src/app/components/ck-monitor/ck-monitor.component.html
frontend/src/app/components/ck-monitor/ck-monitor.component.ts
frontend/src/app/components/ck-workspace/ck-workspace.component.html
frontend/src/app/components/ck-workspace/ck-workspace.component.ts
frontend/src/app/components/create-workflow-modal/create-workflow-modal.component.html
frontend/src/app/components/create-workflow-modal/create-workflow-modal.component.ts
frontend/src/app/models/workflow.ts
frontend/src/app/services/groupTask.service.ts
frontend/src/app/utils/FabricUtils.ts

Reverts encorelab/ck-board#661

Revert "572 add individual work option to generative task workflow"
