src/app/app.component.html, src/app/app.component.scss, src/app/app.component.ts, src/app/utils/Mode.ts
Board defaults to editing mode. But mode can be changed from toolbar floating on the right side of the canvas.
Panning - allows user to move board around while clicking anywhere (including posts)
Editing - Allows panning + moving posts + editing posts
Closes #23
=> Added editing/panning modes

src/app/components/canvas/canvas.component.html
- Change edit mode icon to [edit_note](https://fonts.google.com/icons?icon.query=edit+note)
- Change pan mode icon to [open_with](https://fonts.google.com/icons?icon.query=open+with)
- Alternate when each button appears (pan mode icon appears when edit mode is selected and vice versa)
Closes #55
=> Change icons for edit and pan modes + alternate when each button appears

src/app/components/post/post.component.ts
- You may have noticed that fabric posts had a grey border around them indicating their size. However, the thin grey border was much larger than the actual post itself (yellow area), which was due to a sizing issue.
- Reduced widths of icons and likes/comments values since they were stretching the post unneccesarily.
Closes #134
=> ISSUE-134: Fixed Fabric Post Sizing 

src/app/components/canvas/canvas.component.ts
- Previously, we did not properly update the viewport values since we did not call fabric's `setViewportTransform(vpt)`. 
Closes #189
=> ISSUE-189: Update viewport on pan swipe

src/app/components/canvas/canvas.component.ts
- When posts are being moved and updated, the positional update wasn't taking into account which specific area of the post was clicked. 
Closes #202
=> ISSUE-202: Fixed inaccurate dragging of posts

src/app/app.module.ts, src/app/components/confirm-modal/confirm-modal.component.html, src/app/components/confirm-modal/confirm-modal.component.spec.ts, src/app/components/confirm-modal/confirm-modal.component.ts, src/app/components/post-modal/post-modal.component.html, src/app/components/post-modal/post-modal.component.ts
- Before, we had a 3-dot vertical menu with options to edit and delete the post inside the post modal.
- I scrapped the 3-dot menu and just listed the options as buttons since it doesn't make sense to have a whole menu for just 2 buttons
- Also added a confirm dialog when user wants to delete the post
NOTE: You can test it out on staging instead of having to pull locally now. Check the URL I sent in our slack channel.
Closes #117
=> ISSUE-117: Post modal three dot menu issue

src/app/components/snackbar/snackbar.component.html, src/app/components/snackbar/snackbar.component.scss, src/styles.scss
- Restores snackbar styling and background color.
- Improves visibility of snackbar buttons by removing accent color. Accent color doesn't provide enough contrast with the dark background. Colored buttons do look nice, so in the future we can revisit. Maybe we can think about this more in conjunction with #199.
- Adds a little space between snackbar buttons.
Closes #210
=> ISSUE-210: Fix snackbar CSS/design

src/app/components/canvas/canvas.component.ts, src/app/services/likes.service.ts, src/app/utils/FabricUtils.ts
- Each time the like button is clicked, instead of incrementing/decrementing the value by 1, we check the db for total likes first. This is to stop race conditions which cause the like amounts to be inaccurate.
- Also made liking posts from canvas async which fixes the issue of clicking the like button twice really quickly causing the number to go up by 2. Obviously, this should never happen since one user can only like a post once.
Closes #243
=> ISSUE-243: Make likes from canvas asynchronous

src/app/components/add-board-modal/add-board-modal.component.html, src/app/components/add-board-modal/add-board-modal.component.ts, src/app/components/canvas/canvas.component.html, src/app/components/configuration-modal/configuration-modal.component.html, src/app/models/permissions.ts
- teachers can set the permission when adding a board or updating configuration
Closes #257
=> Add permission to hide buckets from students

backend/src/repository/dalBoard.ts, backend/src/repository/dalBucket.ts, backend/src/repository/dalComment.ts, backend/src/repository/dalGroup.ts, backend/src/repository/dalLike.ts, backend/src/repository/dalNotification.ts, backend/src/repository/dalPost.ts, backend/src/repository/dalProject.ts, backend/src/repository/dalUser.ts, backend/src/repository/dalWorkflow.ts
- Error messages now outputted in the try catch blocks in the backend are more detailed 
- Previously error messages were simply `throw new Error("500")` which did not give info on the specific error, however now the error caught in the catch block is returned
- This will help future debugging if backend problems occur. 
An example output of an error message:
```json
[ERROR] Error: {
"errors": {
"boardID": {
"name": "ValidatorError",
"message": "Path `boardID` is required.",
"properties": {
"message": "Path `boardID` is required.",
"type": "required",
"path": "boardID",
"value": ""
},
"kind": "required",
"path": "boardID",
"value": ""
}
},
"_message": "BoardModel validation failed",
"name": "ValidationError",
"message": "BoardModel validation failed: boardID: Path `boardID` is required." …
```
=> Detailed error messages

frontend/src/app/app-routing.module.ts, frontend/src/app/components/canvas/canvas.component.html, frontend/src/app/components/canvas/canvas.component.ts, frontend/src/app/components/configuration-modal/configuration-modal.component.html, frontend/src/app/components/configuration-modal/configuration-modal.component.ts, frontend/src/app/components/toolbar/toolbar.component.html, frontend/src/app/components/toolbar/toolbar.component.ts
- Creates embedded board that doesn't have back, home, or logout buttons
- Creates distinct URL for that board (replacing /board with /embeddable-board in the URL)
-  Have "Copy Embeddable Board URL" button in the board configurations menu that copies the embedded board URL to clipboard
Closes #296
=> Issue 296 - Create URL for standalone Board

frontend/src/app/components/fabric-post/fabric-post.component.ts, frontend/src/app/components/post-modal/post-modal.component.ts
- Slight tweak in code so that students can edit/delete their own posts (not others)
- Teachers can still edit/delete all posts 
Closes #321
=> Students can edit/delete own posts

backend/src/models/Board.ts, backend/src/models/Trace.ts
I called the branch issue-294, but looking back, I'm not actually sure that this is what 294 was talking about lol. Basically this removes the 
```
Setting "Mixed" for property "TraceModel.event"
Look here for how to disable this message: https://typegoose.github.io/typegoose/docs/api/decorators/model-options/#allowmixed
```
type of warnings that were on the backend.
=> Fix 'Mixed' property warnings

frontend/src/app/components/configuration-modal/configuration-modal.component.ts
Background image settings not being updated in the client after an image is first uploaded.
- Background image settings were not being set in the client after a background image upload. This caused an error when attempting to update the board configuration.
=> Hotfix: Handle null background image settings

frontend/src/app/components/project-dashboard/project-dashboard.component.html
- When personal boards for a project are disabled, the 3 headings are not shown and only shared boards are shown on the teacher dashboard
Closes #366
=> Remove Project Dashboard Headings

backend/src/socket/events/post.events.ts
- Checks if tracing is enabled before attempting to create a trace event for comment deletions.
Closes #432
=> ISSUE-432: Do not create trace event when tracing disabled

frontend/src/app/components/ck-workspace/ck-workspace.component.html
- Unset min-width from angular material raised button (button no longer shrinks)
- Moved group name from workspace task title
Closes #447
=> ISSUE 447 - Fix Text Overflow in Workspace Pane

frontend/src/app/components/canvas/canvas.component.ts
When user scrolls or pans a board with the mousewheel or trackpad, event propagation is stopped. This should prevent the parent of the iframe that an embedded board is loaded in from also scrolling.
Closes #383.
=> feat(canvas): Prevent event propagation of board scroll and pan

backend/src/api/workflows.ts, frontend/src/app/components/ck-monitor/ck-monitor.component.html, frontend/src/app/components/ck-monitor/ck-monitor.component.scss, frontend/src/app/components/ck-monitor/ck-monitor.component.ts, frontend/src/app/models/workflow.ts, frontend/src/app/services/workflow.service.ts
- From the CK-Monitor, teachers can now Cancel Active tasks, which will move the specified group into the "Completed Task" area
- Likewise, Group Tasks in the "Completed task" area can be activated and will move to the "Active Task" area
- No additional changes for Inactive tasks
Closes #467
=> Re-Activate/Cancel Tasks

backend/src/utils/auth.ts, frontend/src/app/components/login/login.component.ts, frontend/src/app/guards/auth.guard.ts, frontend/src/app/guards/board.guard.ts, frontend/src/app/guards/project.guard.ts
- If a user is not logged into CK-Board and tries to navigate to any url (including embedded urls), they will be redirected to the login page, and after they login, they will be redirected to the URL they originally wanted to go to (if they are authorized to)
- Tested for all embeded URL's (todo, ck-monitor, ck-workspace, board)
- Weird bug for board embeddable URLs was occured when it was running the AuthGuard, it would simultaneously run the BoardGoard and ProjectGuard as well. The AuthGuard would redirect to /login momentarily, but would have a race condition with the BoardGuard, which would then send it to /error since you aren't logged in and can't access API. To quickly remedy this, i added a if statement in BoardGuard and ProjectGuard, to see if the user is logged in, if not it …
=> (FIX): Redirect to initial URL upon login

backend/src/repository/dalPost.ts
- Previously we were trying to update posts by passing the flattened version of the post to the `$set` operator, but the `$set` operation doesnt work with dot notation, so this would be the cause for error:
```typescript
{
'$set': {
type: 'BOARD',
title: 'testing bug',
desc: '',
tags: [],
multipleChoice: undefined,
'displayAttributes.position.left': 720,
'displayAttributes.position.top': 219,
'displayAttributes.lock': false
}
}
```
- If we simply pass the fields of the Post that we want to modify to the `$set` operator directly, it will update them successfully, and the post will be downloaded
- Tested for both List and Bucket Views
Closes #507
=> (FIX): Posts can be downloaded from List and Bucket View error-free

frontend/src/app/components/groups/move-group-members/move-group-members.component.html, frontend/src/app/components/groups/move-group-members/move-group-members.component.scss
… position
- Group list view now with a max-height of 500px, overflow will cause scrollable view
- Unassigned group fixed to the left side of modal (not scrollable with the rest of the groups)
Closes #484
=> (FEAT): Scrollable Group list view and Unassigned Group list in fixed position

backend/src/agents/workflow.agent.ts, backend/src/api/workflows.ts, backend/src/models/Workflow.ts, backend/src/socket/events/workflow.events.ts, frontend/src/app/components/add-post-modal/add-post.component.ts, frontend/src/app/components/ck-workspace/ck-workspace.component.html, frontend/src/app/components/ck-workspace/ck-workspace.component.scss, frontend/src/app/components/ck-workspace/ck-workspace.component.ts, frontend/src/app/components/create-workflow-modal/create-workflow-modal.component.html, frontend/src/app/components/create-workflow-modal/create-workflow-modal.component.ts, frontend/src/app/models/workflow.ts, frontend/src/app/services/canvas.service.ts, frontend/src/app/services/groupTask.service.ts
- Generative Task workflow implemented
- Groups now can be given the task of creating a set amount of posts [1, 10] collectively as a group
- Along with post creation, groups can also be given the task of commenting and/or tagging each of the posts they create
- Small caveat with this: The "Submit" button for the generative task workflow is disabled (it removes the posts from the groupTask, causing progress to decrease, which is not what we want). However, once all tasks are complete the "Mark as Complete" button is enabled and the Task can be marked as completed.
- Used sockets to update group progress in real time, hence post show up in CK workspace when other members of the group create a post from their end of CK workspace
- Destinations of where the posts are created can be set as …
=> (FEAT): Implementation Generative task workflow completed

frontend/src/app/utils/highchart.ts
- Diagnostic is now in front of the Re-assessment graph
- Transparency for both area fills reduced to 0.6:
Closes #550
=> (FIX): Change Diagnostic and Re-assessment fill order

backend/src/api/learner.ts, backend/src/models/Learner.ts, backend/src/repository/dalBoard.ts, backend/src/repository/dalLearnerModel.ts, backend/src/repository/dalProject.ts, frontend/src/app/components/ck-monitor/ck-monitor.component.html, frontend/src/app/components/learner-models/learner-models.component.ts, frontend/src/app/models/learner.ts, frontend/src/app/services/learner.service.ts
- Learner Models are now at the project level; they can be viewed from any board and will the same learner models
- Any change in any board is propagated at the project level, so changes are now at the project level rather than the board level
- For all projects before this change, the learner models seen in CK-Monitor will have an aggregate of all the learner models created in the boards individually i.e if previously your project has 3 boards each with 3 learner models, this change will show a total of 9 learner models at the project level
- This will preserve any existing learner models and you can delete then at your choice without having to export and repopulate an existing learner model
Closes #551
=> (FEAT): Learner models set to project level

frontend/src/app/components/ck-workspace/ck-workspace.component.html, frontend/src/app/components/ck-workspace/ck-workspace.component.scss
- State added for peer review workflow when no posts have been reviewed initially as seen below:
Closes #561
=> (FIX): Added state for no reviewed posts in peer review workflow

frontend/src/app/components/canvas/canvas.component.html, frontend/src/app/components/ck-monitor/ck-monitor.component.html, frontend/src/app/components/ck-monitor/ck-monitor.component.scss, frontend/src/app/components/ck-monitor/ck-monitor.component.ts, frontend/src/app/components/learner-models/learner-models.component.html, frontend/src/app/components/learner-models/learner-models.component.scss, frontend/src/app/components/learner-models/learner-models.component.ts, frontend/src/app/utils/highchart.ts
- Students are now able to see the CK-Monitor view both through ck-board and the embedded view
- They can only see their own learner models
- Editing learner models for students is disabled (they cannot export, edit/delete data)
Closes #558
=> CK-Monitor view configured for students

README.md, backend/migrate-mongo-config.ts, backend/migrations/20230117192943-set-post-colors.ts, backend/package-lock.json, backend/package.json, backend/src/constants.ts, backend/src/models/Post.ts, backend/src/socket/events/post.events.ts, backend/src/utils/board.helpers.ts, backend/src/utils/mongo.ts, frontend/src/app/components/add-post-modal/add-post.component.ts, frontend/src/app/components/buckets-modal/buckets-modal.component.ts, frontend/src/app/components/canvas/canvas.component.ts, frontend/src/app/components/fabric-post/fabric-post.component.ts, frontend/src/app/components/html-post/html-post.component.ts, frontend/src/app/components/list-modal/list-modal.component.ts, frontend/src/app/components/post-modal/post-modal.component.ts, frontend/src/app/models/post.ts, frontend/src/app/services/canvas.service.ts, frontend/src/app/services/user.service.ts, frontend/src/app/utils/FabricUtils.ts, frontend/src/app/utils/constants.ts, frontend/src/app/utils/interceptor.ts
- Assign yellow background to student posts and blue background to teacher posts.
- Implemented for all posts across canvas, list view, bucket view and workspace view.
Closes #413
=> ISSUE-413: Change post colour based on author's role

backend/package-lock.json, backend/package.json, backend/src/api/workflows.ts, backend/src/server.ts, backend/src/socket/socket.ts, backend/src/socket/socketManager.ts, backend/src/utils/redis.ts, backend/tsconfig.json
- This PR attempts to fix the socket management issues we are currently facing
- There were a few errors in the code regarding how we were managing rooms and users, which I fixed
- Did thorough testing for a lot of different flows to make sure events are propogated
- Also added a redis-adapter to the socket server so that when we are running servers on scale, different users connected to the same room but on different servers will also receive events
Closes #{ISSUE-NUMBER}
=> WIP: refactor(backend): Socket state management refactor + adding redis adapter

backend/src/socket/socket.ts, frontend/src/app/services/socket.service.ts
Added basic error handling for web socket server and frontend client.
- As source of error is unknown, provided generic handling to catch thrown errors (did not implement showing errors to the user"
- Basic support for dropped wifi appears to already be supported, if you toggle off the wifi in your browser (offline throttling in browser dev tools) then back on over a short duration, the web sockets should continue their connection
**Test**
- No new client or server-side errors
- Handles short duration loss of wifi
Closes #621
=> 621 bug getting econnreset error on production server

backend/src/api/chatHistory.ts, backend/src/models/ChatMessage.ts, backend/src/repository/dalChatMessage.ts, backend/src/server.ts, backend/src/services/vertexAI/index.ts, backend/src/socket/events/ai.events.ts, frontend/src/app/components/create-workflow-modal/create-workflow-modal.component.html, frontend/src/app/components/create-workflow-modal/create-workflow-modal.component.ts
For the AI Assistant, log all chat messages to the data base and create a download button where each teacher can download their own chat history.
-  Create a database schema for saving chat logs, including the teacher's user ID, role (whether user or assistant), the timestamp, the board ID, and the content
- Each time a user creates a prompt, save the prompt with the 'user' role
- Each time the AI assistant creates a response, save the response with the 'assistant' role
- Create a Download Chat History button in the AI assistant tab
- When the download button is pressed, retrieve the entire chat history and save as a CSV file that is downloaded by the client
**Test:**
- Ensure all previous AI Assistant commands work (creating a bucket, move a post, access vote, tag, title, and content …
=> Added download chat history button for AI Assistant

frontend/src/app/components/ck-monitor/ck-monitor.component.ts
Updated calculations of the progress to reflect the progress of generation tasks
- 
Closes #{638}
=> Update the progress on ck-monitor to work with generation tasks

backend/src/api/boards.ts, backend/src/api/projects.ts, backend/src/utils/board.helpers.ts, backend/src/utils/project.helpers.ts
Fixed viewSettings for personal boards
- 
Closes #608
=> Personal Board Access fixed

backend/src/api/chatHistory.ts, backend/src/services/vertexAI/index.ts, backend/src/socket/events/ai.events.ts, frontend/src/app/components/create-workflow-modal/create-workflow-modal.component.ts
- Added abbreviated IDs and replacement and restoration functions before and after the LLM model calls
- Provide the chat history as context
- Switched from chat to freeform (non-chat) gemini
**Test**
Closes #644
=> 644 feature re implement ai assistant with manual history

backend/src/api/auth.ts, backend/src/repository/dalProject.ts, frontend/src/app/components/ck-buckets/ck-buckets.component.html, frontend/src/app/components/ck-buckets/ck-buckets.component.ts, frontend/src/app/components/ck-workspace/ck-workspace.component.scss, frontend/src/app/components/forgot-password/forgot-password.component.ts, frontend/src/app/components/register/register.component.html, frontend/src/app/components/register/register.component.ts, frontend/src/app/components/score-authoring/score-authoring.component.scss, frontend/src/app/services/user.service.ts
**Completed**
- Prevent dragging of posts between buckets in CK Buckets component
- Allow workspace to scroll for large posts
- Added https to password reset link if http is not already specified in the server name
- Cleared email address field when forgot password reset link is requested
- Added https to password reset link if http is not already specified in the server name
- Cleared email address field when forgot password reset link is requested
- Removed enforcement of unique display name
- Set enforcement of unique email
- Display email already in use error if appropriate on registration
**Test**
Closes #672
=> Fix COIL event bugs
